# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprotocol.proto\"D\n\x0bOfferFilter\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\x13\n\x0blower_price\x18\x02 \x01(\x05\x12\x13\n\x0bupper_price\x18\x03 \x01(\x05\"\x1c\n\x08Response\x12\x10\n\x08in_stock\x18\x01 \x01(\x05\x32\x37\n\rOfferSearcher\x12&\n\tFindOffer\x12\x0c.OfferFilter\x1a\t.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocol_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OFFERFILTER._serialized_start=18
  _OFFERFILTER._serialized_end=86
  _RESPONSE._serialized_start=88
  _RESPONSE._serialized_end=116
  _OFFERSEARCHER._serialized_start=118
  _OFFERSEARCHER._serialized_end=173
# @@protoc_insertion_point(module_scope)
